# RUPET Pipeline
# The TIA - Team!
  
steps:
- script: |
    curl https://api.ipify.org/
  displayName: 'IP info'

- task: Xther-Deployment@0
  inputs:
    installDir: '$(Build.SourcesDirectory)/maccli/selenium/'
    resources: 'CHR'
  displayName: 'Xther Deployment'

- task: PowerShell@2
  displayName: 'Running robots'
  inputs:    
    targetType: 'inline'
    script: |
      if ($(imageName) -eq 'macos-10.14')
      {
        chmod 777 '$(Build.SourcesDirectory)/maccli/selenium/chromedriver'
        for ($num = 1; $num -lt $(threads); $num++)
        {
          nohup dotnet maccli/Gsqa.Tools.AiMaps.Console.dll src='maps/ttDemoRupet.aimj' csv='$(Build.SourcesDirectory)/maps/ttDemoRupet.csv' VarLoadSettings.IterationId='$(iterationId)' VarLoadSettings.ApplicationVersion='$(applicationVersion)' VarLoadSettings.BotName='$(botName)' VarLoadSettings.BotAuthor='$(botAuthor)' &
        }
        dotnet maccli/Gsqa.Tools.AiMaps.Console.dll src='maps/ttDemoRupet.aimj' csv='$(Build.SourcesDirectory)/maps/ttDemoRupet.csv' VarLoadSettings.IterationId='$(iterationId)' VarLoadSettings.ApplicationVersion='$(applicationVersion)' VarLoadSettings.BotName='$(botName)' VarLoadSettings.BotAuthor='$(botAuthor)'
      }
      elseif ($(imageName) -eq'windows-latest')
      {
        Write-Host "Windows not implemented"
      }